////////////////////////////////////////////////////
// Low-level literal syntax
digit      : /[0-9]/
digits     : /[0-9]+/
hex_digit  : /[0-9a-fA-F]/
hex_digits : /[0-9a-fA-F]+/
letter     : /[a-zA-Z]/
letters    : /[a-zA-Z]+/
underscore : /[_]/
true       : "true"
false      : "false"

// Literals
bool_literal : true | false
decimal_literal : digits
hexadecimal_literal : "0x" hex_digits
?integer_literal : decimal_literal | hexadecimal_literal
negated_integer_literal : "-" integer_literal
?posneg_integer_literal : integer_literal | negated_integer_literal
float_literal : /[-+]?[0-9]+[.][0-9]*([eE][-+]?[0-9]+)?/
string_literal  : ESCAPED_STRING
?constant_literal : bool_literal | posneg_integer_literal | float_literal | string_literal
unknown_dim_literal : "?"

// Identifier syntax (loosely following MLIR conventions)
bare_id : /[_a-zA-Z][_0-9a-zA-Z]*/
suffix_id : digits | bare_id
identifier : "%" suffix_id ("#" digits)?

// Scalar types
!float_type : "f16" | "f32" | "f64"
!int_type : "i8" | "i16" | "i32"
!uint_type : "u8" | "u16" | "u32"
!bool_type : "bool"
!unknown_type : "UNKNOWN"
?standard_type : float_type | int_type | uint_type | bool_type | unknown_type

// Any type
any_type : "?"

// Built-in enumerations
!schedule_type : "PARALLEL" | "FORWARD" | "BACKWARD"
?enum_literal : schedule_type

// Language built-in types
?dim : posneg_integer_literal | unknown_dim_literal
!dim_or_end : dim | "None"
dim_list: dim ("," dim)*

interval_type : ("spst.")? "interval" "<" dim_or_end "," dim_or_end ">" | dim_or_end ":" dim_or_end
computation_interval : "[" interval_type ("," interval_type)* "]"
multi_interval_type : "[" interval_type ("," interval_type)* "]"

extent_offset_tuple : "(" dim ("," dim)* ")"
extent_tuple : extent_offset_tuple
extent_tuple_list : extent_tuple ("," extent_tuple)*
extent_type : ("spst.")? "extent" "<" extent_tuple_list ">" | "{" extent_tuple_list "}"

domain_list : (interval_type | unknown_dim_literal) ("," (interval_type | unknown_dim_literal))*
domain_type : ("spst.")? ("domain" | "cartesian") "<" domain_list ">" | "[" domain_list "]"
view_type : ("spst.")? "view" "<" domain_type "," extent_type "," standard_type ">"
field_type: ("spst.")? "field" "<" domain_type "," standard_type ">"


?builtin_type : view_type | domain_type | extent_type | interval_type | multi_interval_type | computation_interval
?field_or_scalar_type : view_type | field_type | standard_type | any_type

////////////////////////////////////////////////////
// Operators and operator precedence
// Adapted and reduced from Lark's Python grammar
// https://github.com/lark-parser/lark/blob/88fe0fdcdccc9f8856e96fd6fe9d28ae3cb4f64b/lark/grammars/python.lark

?test : or_test
      | or_test "if" or_test "else" test -> ternary_op

?or_test: and_test ("or" or_test) -> binary_op_logical_or
        | and_test
?and_test: not_test_ ("and" and_test) -> binary_op_logical_and
         | not_test_
?not_test_: "not" not_test_ -> not_test
          | comparison
?comparison: expr (_comp_op comparison) -> comparison
           | expr

?expr: or_expr
?or_expr: xor_expr ("|" or_expr) -> binary_op_or
        | xor_expr
?xor_expr: and_expr ("^" xor_expr) -> binary_op_xor
         | and_expr
?and_expr: shift_expr ("&" and_expr) -> binary_op_and
         | shift_expr
?shift_expr: arith_expr (_shift_op shift_expr) -> binary_op
           | arith_expr

?arith_expr: term (_add_op arith_expr) -> binary_op
           | term
?term: factor (_mul_op term) -> binary_op
     | factor
?factor: _unary_op factor -> unary_op
       | power

!_unary_op: "+"|"-"|"~"
!_add_op: "+"|"-"
!_shift_op: "<<"|">>"
!_mul_op: "*"|"/"|"%"
!_comp_op: "<"|">"|"=="|">="|"<="|"!="

?power: atom_expr ("**" factor)+ -> binary_op_pow
      | atom_expr

?atom_expr: bare_id "(" [call_arguments] ")"         -> call
          | identifier "[" subscript_slice "]"  -> subscript
          | atom_expr "." bare_id               -> getattr
          | atom

?atom: identifier
     | constant_literal
     | "(" test ")"

call_arguments: test ("," test)*

////////////////////////////////////////////////////
// Common syntactic elements
id_list : identifier ("," identifier)*
?params : "(" id_list? ")"
type_list : field_or_scalar_type ("," field_or_scalar_type)*
type_info : ":" field_or_scalar_type ("->" field_or_scalar_type)?
type_list_info : ":" type_list ("->" type_list)?

schedule_keyword : "schedule"
interval_keyword : "interval"
attr : schedule_keyword "=" schedule_type | interval_keyword "=" computation_interval

attributes : "{" attr? ("," attr)* "}"

// Define program
program : id_list "=" "spst.program" ("@" bare_id)? params (attributes)? type_list_info program_body

// Define computation
computation : id_list "=" "spst.computation" params attributes type_list_info computation_body

// Define stencil statement
statement : id_list "=" "spst.statement" params (attributes)? type_list_info statement_body

////////////////////////////////////////////////////
// Define contents of stencil statements
subscript_slice : posneg_integer_literal ("," posneg_integer_literal)*
value_expr : test     // Basic value type. See operator precedence for more information
assign_expr : id_list "=" value_expr (";")? type_info?
return_expr : ("spst.")? "return" value_expr  ("," value_expr)* (";")? type_list_info?
?statement_contents : assign_expr | return_expr

materialize_op : identifier "=" "spst.materialize" "(" identifier ")" type_info?

if_op : id_list "=" "spst.if" "(" identifier ")" type_info? computation_body (elif_block)* (else_block)?
elif_block : "elif" "(" identifier ")" computation_body
else_block : "else" computation_body

////////////////////////////////////////////////////
// AST tree structure
program_body : "{" computation* return_expr "}"
computation_body : "{" (statement | if_op | materialize_op | return_expr)* "}"
statement_body : "{" statement_contents* "}"

?start: program

////////////////////////////////////////////////////
// Lark imports
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%import common.NEWLINE

// Things to ignore: whitespace, single-line comments, multi-line comments
COMMENT : "//" /(.)+/ NEWLINE
MULTILINE_COMMENT: /\/\*(\*(?!\/)|[^*])*\*\//
%ignore WS
%ignore COMMENT
%ignore MULTILINE_COMMENT
